# filebeat.yml

name: "api-filebeat"

# Searches for docker containers matching a certain criteria
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              # Will discover any Docker container with tags of filebeat="true"
              docker.container.labels.filebeat: "true"
          config:
            - type: container
              json.keys_under_root: false
              json.add_error_key: true
              paths:
                - /usr/share/docker-logs/data/${data.docker.container.id}/*.log

# Inputs gets called after autodiscover finds something
filebeat.inputs:
  - type: docker
    containers:
      # Type of stream to look for
      stream: "stderr"
      ids:
        - "*"

processors:
  # Add all docker metadata
  - add_docker_metadata: ~

# ES Settings
setup.template.settings:
  index.number_of_shards: 3
setup.template.overwrite: true

# Add tags to give more context about the machine
# Example:
# backend
# web-server
tags: ["backend", "web-server"]

# Add specific fields to get more context about the log
# Example:
# instance_id: i-10a123
# region: us-east-1
fields:
  instance_id: i-10a64379
  region: us-east-1

output.elasticsearch:
  # if your elasticsearch is local you can change it to 127.0.0.1:9200
  hosts: ["elasticsearch:9200"]
  template:
    name: "filebeat"
    path: "fields.yml"
    overwrite: false
  # protocol: "http"
  # identification required for X-pack
  # username: "my_login"
  # password: "my_password"

# Write Filebeat own logs only to file to avoid catching them with itself in docker log files
logging.level: error
logging.to_files: true
logging.to_syslog: false
loggins.metrice.enabled: false
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
